name: Multiverse-Hardcore
main: gg.ggs.jackalgaming.mvhardcore.MultiverseHardcore
version: 0.0.1
api-version: 1.13
author: jackal-gaming
depend: ['Multiverse-Core']
description: Create team-based multiverse hardcore worlds

commands:
  mvhc:
    description: Base Multiverse-Hardcore Command
    usage: /<command>
  mvhchelp:
    description: Returns a nice help menu
    aliases: ['mvhch', 'mvhc help']
    usage: /<command>
  mvhclist:
    description: Returns list of registered hardcore worlds
    aliases: ['mvhcl', 'mvhc list']
    usage: /<command>
  mvhcinfo:
    description: Returns detailed information about the specified hardcore world
    aliases: ['mvhci', 'mvhc info']
    usage: /<command> [WORLD]
  mvhcregister:
    description: Register an existing Multiverse world as a hardcore world
    aliases: ['mvhc register', 'mvhc link']
    usage: /<command> [WORLD]