name: Multiverse-Hardcore
main: gg.ggs.jackalgaming.mvhardcore.MultiverseHardcore
version: 0.0.1
api-version: 1.13
author: jackal-gaming
depend: ['Multiverse-Core']
description: Create team-based multiverse hardcore worlds

commands:
  mvhc help:
    description: Returns a nice help menu
    aliases: [mvhch]
    usage: /<command>
  mvhc list:
    description: Returns list of registered hardcore worlds
    aliases: [mvhcl]
    usage: /<command>
  mvhc info:
    description: Returns detailed information about the specified hardcore world
    aliases: [mvhci]
    usage: /<command>
  mvhc register:
    description: Register an existing Multiverse world as a hardcore world
    aliases: [mvhc link]
    usage: /<command>